### Fetch all tasks
GET http://localhost:3200/tasks
Content-Type: application/json

### Create a new task
POST http://localhost:3200/tasks
Content-Type: application/json

{
  "title": "going to the gym",
  "date": "2024-10-01",
  "description": "Description of going to the gym",
  "priority": "medium",
  "status": "todo"
}

### Update a task
PUT http://localhost:3200/tasks
Content-Type: application/json

{
    "id": "a53d8958-68c3-40e4-adee-f313b5537388",
    "status": "inProgress"
}